### ISSUE TITLE
Very interesting demo

### ISSUE THREAD

**Issue by airsyuan** [Xzzit/ChipGAN-pytorch#1]
Hi, this is quite an interesting demo. But when I use the released .pth file in save_model raising an Error "_pickle.UnpicklingError: invalid load key, 'v'".  Could you offer some advice, many thanks.

**Comment by Xzzit** [comment]
Hi, thanks for using my model!
Did you write your own test code or did you use the “paint.py” code I upload recently?
I have tried the code on different PC and it works for me.

**Comment by airsyuan** [comment]
> Hi, thanks for using my model!
> Did you write your own test code or did you use the “paint.py” code I upload recently?
> I have tried the code on a different PC and it works for me.

Thanks, it works after changing a platform.
