### ISSUE TITLE
How to get the pretrained hed model?

### ISSUE THREAD

**Issue by jueming0731** [Xzzit/ChipGAN-pytorch#2]
hh

**Comment by Orangebyplane** [comment]
hh

**Comment by Xzzit** [comment]
You can find the link in the description. If it doesn't work for you, please contact me~

**Comment by jueming0731** [comment]
Thanks!

**Comment by Xzzit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
