### ISSUE TITLE
打不开您的savemodle文件 

### ISSUE THREAD

**Issue by aster451** [Xzzit/ChipGAN-pytorch#3]
您好，我打不开您的savemodle文件 有新的连接可以打开么？

**Comment by Xzzit** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Xzzit** [comment]
您好，预训练模型用的是谷歌云盘存的，国内可能打不开，我现在去百度网盘存一份，稍等！

**Comment by aster451** [comment]
哇！万分感谢！！&nbsp; 您用到的模型可以都存一份么 下面那个chipGAN Models也打不开






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiang ***@***.***&gt;; 
发送时间: 2022年9月18日(星期天) 下午4:19
收件人: ***@***.***&gt;; 
抄送: "赵敏 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xzzit/ChipGAN-PyTorch1.8-] 打不开您的savemodle文件  (Issue #3)





 
您好，预训练模型用的是谷歌云盘存的，国内可能打不开，我现在去百度网盘存一份，稍等！

**Comment by Xzzit** [comment]
链接: https://pan.baidu.com/s/1NsmYiGRMQ3MN-DvXtUpIGw?pwd=qj9q 提取码: qj9q
所有的模型都在里面了，您看看这个可以用吗？

**Comment by aster451** [comment]
太感谢您了 我去试试！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiang ***@***.***&gt;; 
发送时间: 2022年9月18日(星期天) 下午4:28
收件人: ***@***.***&gt;; 
抄送: "赵敏 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xzzit/ChipGAN-PyTorch1.8-] 打不开您的savemodle文件  (Issue #3)





 
链接: https://pan.baidu.com/s/1NsmYiGRMQ3MN-DvXtUpIGw?pwd=qj9q 提取码: qj9q
 所有的模型都在里面了，您看看这个可以用吗？

**Comment by aster451** [comment]
麻烦您了 ，万分感谢！期待您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiang ***@***.***&gt;; 
发送时间: 2022年9月18日(星期天) 下午4:12
收件人: ***@***.***&gt;; 
抄送: "赵敏 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xzzit/ChipGAN-PyTorch1.8-] 打不开您的savemodle文件  (Issue #3)





 这是来自QQ邮箱的假期自动回复邮件。 
 &nbsp; 
 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
